FROM node:16

WORKDIR /app

# Install dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install

# Copy React app
COPY . .

# Expose React port
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
