FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirement.txt .
RUN pip install  -r requirement.txt

# Copy FastAPI app
COPY . .

# Expose FastAPI port
EXPOSE 8000

# Run the FastAPI app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
